### ISSUE TITLE
推荐你用用智邮记微信小程序,可以实现招行信用卡等账单的自动记账

### ISSUE THREAD

**Issue by bawfnje** [HADB/feidee-auto-bot#1]
推荐你用用智邮记微信小程序,可以实现招行信用卡等账单的自动记账

**Comment by HADB** [comment]
不过我已经在随手记上记了好多年的数据了，没办法切换记账软件了

**Comment by bawfnje** [comment]
那更得用智邮记微信小程序了，它本身不记录账单数据，是将微信、支付宝以及招行等信用卡及借记卡的账单邮件自动记录到随手记app上。代替你手工记账的。
